version: "3"

services:
  db:
    image: mysql:5.7
    ports:
      - "3336:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8080:80"
    depends_on:
      - db
